// src/components/game/MoneyDisplay.tsx
interface MoneyDisplayProps {
  value: number;
  imgSrc?: string;
  style?: React.CSSProperties;
}

export default function MoneyDisplay({
  value,
  imgSrc,
  style,
}: MoneyDisplayProps) {
  const formatted =
    value?.toLocaleString("en-US", {
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }) ?? "0";

  return (
    <div className="flex w-full items-center justify-between" style={style}>
      {imgSrc && <img style={{ height: 22 }} src={imgSrc} alt="label" />}
      <span className="money-glow m-0 flex items-center justify-center text-2xl text-[#f0e68c]">
        {formatted}
      </span>
    </div>
  );
}

// src/app/components/money-display/money-display.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-money-display',
  standalone: true,
  imports: [],
  templateUrl: './money-display.component.html',
  styleUrl: './money-display.component.scss',
})
export class MoneyDisplayComponent {
  @Input() value = 0;
}

<div class="w-100 d-flex align-items-center justify-content-between">
  <img *ngIf="imgSrc" style="height: 22px" class="label-image" [src]="imgSrc" />
  <span class="money">{{ value | number: "1.0-2" : "en-US" }}</span>
</div>
