// src/app/containers/slot-machine/slot-machine.component.ts
import { Component, ViewChild } from '@angular/core';
import { BG_COLOR } from '../../shared/color';
import { NgClass, NgOptimizedImage } from '@angular/common';
import {
  COUNTDOWN_TIME,
  SpinButtonComponent,
} from '../../components/spin-button/spin-button.component';
import { BetButtonComponent } from '../../components/bet-button/bet-button.component';
import { ClearButtonComponent } from '../../components/clear-button/clear-button.component';
import { FaqButtonComponent } from '../../components/faq-button/faq-button.component';
import { MaxBetButtonComponent } from '../../components/max-bet-button/max-bet-button.component';
import { ChipComponent } from '../../components/chip/chip.component';
import { GameHistoryComponent } from '../../components/game-history/game-history.component';
import { MoneyDisplayComponent } from '../../components/money-display/money-display.component';
import { ApiService, WalletInfo } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';
import { BetResult, UserBalance } from '../../models/game-slot.model';
import { SocketService } from '../../services/socket.service';
import { YourLuckHereTextComponent } from '../../components/your-luck-here-text/your-luck-here-text.component';
import { Reels } from '../reels/reels';
import { LightComponent } from '../../components/light/light.component';

@Component({
  selector: 'app-slot-machine',
  standalone: true,
  imports: [
    NgClass,
    SpinButtonComponent,
    SpinButtonComponent,
    BetButtonComponent,
    ClearButtonComponent,
    FaqButtonComponent,
    MaxBetButtonComponent,
    ChipComponent,
    GameHistoryComponent,
    MoneyDisplayComponent,
    YourLuckHereTextComponent,
    NgOptimizedImage,
    Reels,
    LightComponent,
  ],
  templateUrl: './slot-machine.component.html',
  styleUrl: './slot-machine.component.scss',
})
export class SlotMachineComponent {
  public playerScore = 10;
  public knobClicked = false;
  public isSpinning = false;

  public debitedMoney: number | string = 0;
  public showDebitMoney = false;

  selectedChipValue = 0;
  totalBet = 0;
  totalWin = 0;
  currentWin = 0;
  userBalance: UserBalance;
  currentWallet: string;
  history: boolean[] = Array.from({ length: 10 }, () => Math.random() < 0.5);

  private knobPullSound = '../../../assets/audio/knob-pull.mp3';
  private spinningSound = '../../../assets/audio/spinning.mp3';
  private payOutSound = '../../../assets/audio/pay-out.wav';

  @ViewChild(Reels) reels: Reels;

  @ViewChild('wheelCell1', { static: false }) wheel1;
  @ViewChild('wheelCell2', { static: false }) wheel2;
  @ViewChild('wheelCell3', { static: false }) wheel3;
  @ViewChild('debugWheel1', { static: false }) debugWheel1;
  @ViewChild('debugWheel2', { static: false }) debugWheel2;
  @ViewChild('debugWheel3', { static: false }) debugWheel3;

  constructor(
    private readonly apiService: ApiService,
    private readonly authService: AuthService,
    private readonly socketService: SocketService,
  ) {
    this.authService.login().subscribe((userInfo) => {
      console.log(userInfo);
      this.socketService.connect();
      this.apiService.joinRoom('main').subscribe((r: WalletInfo) => {
        this.currentWallet = r.playMode;
        this.totalWin = r.userBalance;
        this.fetchHistory();
      });
      this.apiService.getUserBalance().subscribe((b) => {
        this.userBalance = b;
      });
      // this.apiService
      //   .getHistory({ wallet: this.currentWallet, userId: '' })
      //   .subscribe((h) => console.log(h));
      // this.authService.getAsset().subscribe((a) => {
      //   console.log(a);
      // });
      //
    });
  }

  fetchHistory(): void {
    this.apiService
      .getHistory({ wallet: this.currentWallet })
      .subscribe((h) => console.log({ h }));
  }

  getCurrentUserBalance(): number {
    return this.userBalance?.[this.currentWallet]?.VND;
  }

  clearBet(): void {
    this.totalBet = 0;
    this.selectedChipValue = 0;
  }

  maxBet(): void {
    this.totalBet = this.getCurrentUserBalance();
    this.selectedChipValue = 0;
  }

  public knobPulled() {
    this.apiService.placeOrder(this.totalBet).subscribe((res: BetResult) => {
      console.log({ betResult: res });
      if (res.betResult === 'win') {
        this.reels.startPlay(res.betResultType);
      } else {
        this.reels.startPlay();
      }
      this.fetchHistory();
    });

    if (this.playerScore > 0) {
      this.knobClicked = true;
      this.showDebitMoney = false;
      this.isSpinning = true;
      this.reset();
      this.resetBgColor();
      this.knobPullPlay(this.knobPullSound);
      setTimeout(() => (this.knobClicked = false), 1500);
      // setTimeout(() => {
      //   this.startSpinning();
      // }, 1000);
      this.playerScore--;
      this.debitedMoney = -1;

      this.showDebitMoney = true;
    }
  }

  private knobPullPlay(src) {
    this.playAudio(src);
  }
  private spinningPlay(src) {
    this.playAudio(src);
  }
  private payoutPlay(src) {
    this.playAudio(src);
  }

  public playAudio(src) {
    let audio = new Audio();
    audio.src = src; // "../../../assets/audio/spinning.mp3";
    audio.load();
    audio.play();
  }

  selectChip(value: number): void {
    this.selectedChipValue = value;
  }

  onBet(): void {
    this.totalBet += this.selectedChipValue;
    this.selectedChipValue = 0;
  }

  private reset() {}

  private resetBgColor() {}

  onDragStart(event: DragEvent) {
    event.dataTransfer.setData('text', (event.target as HTMLElement).id);
  }

  onDragOver(event: DragEvent) {
    event.preventDefault();
  }

  onDrop(event: DragEvent) {
    const { target } = event;
    const { childNodes } = target as HTMLElement;
    if (childNodes.length > 0) {
      (target as HTMLElement).removeChild(childNodes[0]);
    }
    (target as HTMLElement).appendChild(
      document
        .getElementById(event.dataTransfer.getData('text'))
        .cloneNode(true),
    );
  }
}

<div class="slot-machine">
  <!--  <img-->
  <!--    class="light"-->
  <!--    id="left-light"-->
  <!--    src="/assets/images/left-light.png"-->
  <!--    alt="left light"-->
  <!--  />-->
  <app-light id="left-light"></app-light>
  <img
    class="light"
    id="right-light"
    src="/assets/images/right-light.png"
    alt="right light"
  />

  <app-your-luck-here-text id="your-luck-here"></app-your-luck-here-text>

  <div #wheelWrapper class="slot-wheel-wrapper">
    <app-reels
      #appReels
      [width]="wheelWrapper.clientWidth - 16"
      [height]="wheelWrapper.clientHeight - 16"
      class="reels-comp"
    ></app-reels>
    <!--    <div class="wheel-container">-->
    <!--      <div #wheelCell1 class="wheel">-->
    <!--        &lt;!&ndash;        <img&ndash;&gt;-->
    <!--        &lt;!&ndash;          class="wheel-light"&ndash;&gt;-->
    <!--        &lt;!&ndash;          ngSrc="/assets/images/wheel-light.png"&ndash;&gt;-->
    <!--        &lt;!&ndash;          alt="wheel light"&ndash;&gt;-->
    <!--        &lt;!&ndash;          height="63"&ndash;&gt;-->
    <!--        &lt;!&ndash;          width="123"&ndash;&gt;-->
    <!--        &lt;!&ndash;        />&ndash;&gt;-->
    <!--      </div>-->
    <!--    </div>-->

    <!--    <div class="wheel-container">-->
    <!--      <div #wheelCell2 class="wheel">-->
    <!--        &lt;!&ndash;        <img&ndash;&gt;-->
    <!--        &lt;!&ndash;          class="wheel-light"&ndash;&gt;-->
    <!--        &lt;!&ndash;          ngSrc="/assets/images/wheel-light.png"&ndash;&gt;-->
    <!--        &lt;!&ndash;          alt="wheel light"&ndash;&gt;-->
    <!--        &lt;!&ndash;          height="63"&ndash;&gt;-->
    <!--        &lt;!&ndash;          width="123"&ndash;&gt;-->
    <!--        &lt;!&ndash;        />&ndash;&gt;-->
    <!--      </div>-->
    <!--    </div>-->

    <!--    <div class="wheel-container">-->
    <!--      <div #wheelCell3 class="wheel">-->
    <!--        &lt;!&ndash;        <img&ndash;&gt;-->
    <!--        &lt;!&ndash;          class="wheel-light"&ndash;&gt;-->
    <!--        &lt;!&ndash;          ngSrc="/assets/images/wheel-light.png"&ndash;&gt;-->
    <!--        &lt;!&ndash;          alt="wheel light"&ndash;&gt;-->
    <!--        &lt;!&ndash;          height="63"&ndash;&gt;-->
    <!--        &lt;!&ndash;          width="123"&ndash;&gt;-->
    <!--        &lt;!&ndash;        />&ndash;&gt;-->
    <!--      </div>-->
    <!--    </div>-->

    <!--    <div-->
    <!--      [ngClass]="{-->
    <!--        active: line1Score !== 0 && line1Score === getMaxScore(),-->
    <!--      }"-->
    <!--      class="wheel-line top"-->
    <!--    ></div>-->
    <!--    <div-->
    <!--      [ngClass]="{-->
    <!--        active: line2Score !== 0 && line2Score === getMaxScore(),-->
    <!--      }"-->
    <!--      class="wheel-line center"-->
    <!--    ></div>-->
    <!--    <div-->
    <!--      [ngClass]="{-->
    <!--        active: line3Score !== 0 && line3Score === getMaxScore(),-->
    <!--      }"-->
    <!--      class="wheel-line bottom"-->
    <!--    ></div>-->
  </div>

  <app-faq-button id="faq-button"></app-faq-button>
  <app-bet-button (onclick)="onBet()" id="bet-button">bet</app-bet-button>

  <app-spin-button
    (onclick)="!reels.running && knobPulled()"
    id="spin-button"
  ></app-spin-button>

  <app-clear-button (onclick)="clearBet()" id="clear-button"></app-clear-button>
  <app-max-bet-button
    (onclick)="maxBet()"
    id="max-bet-button"
  ></app-max-bet-button>

  <app-chip
    [selectedValue]="selectedChipValue"
    (onclick)="selectChip(10)"
    id="chip-10"
    [value]="10"
  ></app-chip>
  <app-chip
    [selectedValue]="selectedChipValue"
    (onclick)="selectChip(20)"
    id="chip-20"
    [value]="20"
  ></app-chip>
  <app-chip
    [selectedValue]="selectedChipValue"
    (onclick)="selectChip(50)"
    id="chip-50"
    [value]="50"
  ></app-chip>
  <app-chip
    [selectedValue]="selectedChipValue"
    (onclick)="selectChip(100)"
    id="chip-100"
    [value]="100"
  ></app-chip>
  <app-chip
    [selectedValue]="selectedChipValue"
    (onclick)="selectChip(250)"
    id="chip-250"
    [value]="250"
  ></app-chip>
  <app-chip
    [selectedValue]="selectedChipValue"
    (onclick)="selectChip(500)"
    id="chip-500"
    [value]="500"
  ></app-chip>

  <app-game-history [history]="history" id="game-history"></app-game-history>

  <app-money-display
    style="width: 190px"
    [imgSrc]="'/assets/images/total-bet-label.png'"
    [value]="totalBet"
    id="total-bet-number"
  ></app-money-display>

  <app-money-display
    style="width: 138px"
    [imgSrc]="'/assets/images/credit-label.png'"
    [value]="totalWin"
    id="total-win-number"
  ></app-money-display>

  <app-money-display
    [value]="getCurrentUserBalance()"
    id="balance-number"
  ></app-money-display>

  <app-money-display
    style="width: 138px"
    [imgSrc]="'/assets/images/win-label.png'"
    [value]="currentWin"
    id="current-win-number"
  ></app-money-display>
</div>

// src-react/components/SlotMachine.tsx
import { useCallback, useRef, useState } from 'react';
import Reels, { type ReelsHandle } from './Reels';
import SpinButton from './SpinButton';
import ImageButton from './ImageButton';
import Chip from './Chip';
import GameHistory from './GameHistory';
import MoneyDisplay from './MoneyDisplay';
import FaqModal from './FaqModal';
import type { UserBalance } from '../models/game-slot.model';
import './SlotMachine.scss';

interface SlotMachineProps {
  userBalance: UserBalance | null;
  currentWallet: string;
  totalWin: number;
  onLoadingMessage?: (msg: string) => void;
  onLoadingDone?: () => void;
}

export default function SlotMachine({
  userBalance,
  currentWallet,
  totalWin,
  onLoadingMessage,
  onLoadingDone,
}: SlotMachineProps) {
  const reelsRef = useRef<ReelsHandle>(null);
  const wheelWrapperRef = useRef<HTMLDivElement>(null);

  const [selectedChipValue, setSelectedChipValue] = useState(0);
  const [totalBet, setTotalBet] = useState(0);
  const [currentWin] = useState(0);
  const [playerScore, setPlayerScore] = useState(10);
  const [history] = useState<boolean[]>(() =>
    Array.from({ length: 10 }, () => Math.random() < 0.5),
  );

  const [reelDimensions, setReelDimensions] = useState({ width: 484, height: 254 });

  const wheelRef = useCallback((node: HTMLDivElement | null) => {
    if (node) {
      setReelDimensions({
        width: node.clientWidth - 16,
        height: node.clientHeight - 16,
      });
      (wheelWrapperRef as any).current = node;
    }
  }, []);

  function getCurrentUserBalance(): number {
    if (!userBalance || !currentWallet) return 0;
    return (userBalance as any)[currentWallet]?.VND ?? 0;
  }

  function clearBet() {
    setTotalBet(0);
    setSelectedChipValue(0);
  }

  function maxBet() {
    setTotalBet(getCurrentUserBalance());
    setSelectedChipValue(0);
  }

  function onBet() {
    setTotalBet((prev) => prev + selectedChipValue);
    setSelectedChipValue(0);
  }

  function knobPulled() {
    reelsRef.current?.startPlay(150);
    if (playerScore > 0) {
      playAudio('/assets/audio/knob-pull.mp3');
      setPlayerScore((prev) => prev - 1);
    }
  }

  function playAudio(src: string) {
    const audio = new Audio();
    audio.src = src;
    audio.load();
    audio.play();
  }

  const chipValues = [10, 20, 50, 100, 250, 500];

  return (
    <div className="slot-machine">
      <img className="light" id="left-light" src="/assets/images/left-light.png" alt="left light" />
      <img className="light" id="right-light" src="/assets/images/right-light.png" alt="right light" />

      <div id="your-luck-here" className="w-100" style={{ position: 'absolute', top: 75, width: 198 }}>
        <img className="w-100" src="/assets/images/your-luck-here.png" alt="your luck here" />
        <img className="position-absolute text-bg" src="/assets/images/your-luck-here-bg.png" alt="bg" style={{ top: 2, left: 0, width: '100%' }} />
      </div>

      <div ref={wheelRef} className="slot-wheel-wrapper">
        <Reels
          ref={reelsRef}
          width={reelDimensions.width}
          height={reelDimensions.height}
          onLoadingMessage={onLoadingMessage}
          onLoadingDone={onLoadingDone}
        />
      </div>

      <FaqModal className="faq-button-pos" />

      <div id="bet-button">
        <ImageButton
          defaultImage="/assets/buttons/bet-mouse-up.png"
          pressedImage="/assets/buttons/bet-mouse-down.png"
          onClick={onBet}
          label={{ src: '/assets/images/bet-label.png', alt: 'bet label' }}
        />
      </div>

      <div id="spin-button">
        <SpinButton onClick={() => !reelsRef.current?.running && knobPulled()} />
      </div>

      <div id="clear-button">
        <ImageButton
          defaultImage="/assets/buttons/clear-mouse-up.png"
          pressedImage="/assets/buttons/clear-mouse-down.png"
          onClick={clearBet}
          label={{ src: '/assets/images/clear-label.png', alt: 'clear label' }}
        />
      </div>

      <div id="max-bet-button">
        <ImageButton
          defaultImage="/assets/buttons/max-bet-mouse-up.png"
          pressedImage="/assets/buttons/max-bet-mouse-down.png"
          onClick={maxBet}
          label={{ src: '/assets/images/max-bet-label.png', alt: 'max bet label' }}
        />
      </div>

      {chipValues.map((val) => (
        <div key={val} id={`chip-${val}`}>
          <Chip
            value={val}
            selectedValue={selectedChipValue}
            onClick={() => setSelectedChipValue(val)}
          />
        </div>
      ))}

      <div id="game-history">
        <GameHistory history={history} />
      </div>

      <div id="total-bet-number" style={{ width: 190 }}>
        <MoneyDisplay imgSrc="/assets/images/total-bet-label.png" value={totalBet} />
      </div>

      <div id="total-win-number" style={{ width: 138 }}>
        <MoneyDisplay imgSrc="/assets/images/credit-label.png" value={totalWin} />
      </div>

      <div id="balance-number">
        <MoneyDisplay value={getCurrentUserBalance()} />
      </div>

      <div id="current-win-number" style={{ width: 138 }}>
        <MoneyDisplay imgSrc="/assets/images/win-label.png" value={currentWin} />
      </div>
    </div>
  );
}
