// src/app/components/game-history/game-history.component.ts
import { Component, Input } from '@angular/core';
import { NgForOf, NgIf } from '@angular/common';

@Component({
  selector: 'app-game-history',
  standalone: true,
  imports: [NgForOf, NgIf],
  templateUrl: './game-history.component.html',
  styleUrl: './game-history.component.scss',
})
export class GameHistoryComponent {
  @Input() history: boolean[] = [true, false, false, true, true, false];
}

<div class="d-flex gap-1">
  <div *ngFor="let i of history">
    <img
      style="width: 18px"
      alt="win-img"
      *ngIf="i"
      src="/assets/images/white-circle.png"
    />
    <img
      style="width: 18px"
      alt="win-img"
      *ngIf="!i"
      src="/assets/images/black-circle.png"
    />
  </div>
</div>

// src/components/game/GameHistory.tsx
interface GameHistoryProps {
  history: boolean[];
}

export default function GameHistory({ history }: GameHistoryProps) {
  return (
    <div className="flex gap-1">
      {history.map((win, i) => (
        <div key={i}>
          <img
            className="w-[18px]"
            alt={win ? 'win' : 'loss'}
            src={win ? '/assets/images/white-circle.png' : '/assets/images/black-circle.png'}
          />
        </div>
      ))}
    </div>
  );
}
