// src/components/game/WinConditions.tsx
import './WinConditions.scss';

const winConditions = [
  { image: '/assets/symbols/Bell.png', line: 'Any line', ratio: '150%' },
  { image: '/assets/symbols/Cherries.png', line: 'Any line', ratio: '100%' },
  { image: '/assets/symbols/Grape.png', line: 'Any line', ratio: '90%' },
  { image: '/assets/symbols/Lemon.png', line: 'Any line', ratio: '80%' },
  { image: '/assets/symbols/Melon.png', line: 'Any line', ratio: '70%' },
  { image: '/assets/symbols/Orange.png', line: 'Any line', ratio: '60%' },
  { image: '/assets/symbols/Scatter.png', line: 'Any line', ratio: '50%' },
  { image: '/assets/symbols/7.png', line: 'Any line', ratio: 'Jackpot' },
];

export default function WinConditions() {
  return (
    <div className="container">
      <div className="win-conditions">
        <div className="table-responsive">
          <table className="table table-bordered">
            <tbody>
              <tr>
                {winConditions.map((c, i) => (
                  <td key={i} className="text-center">
                    <img src={c.image} alt="symbol" className="symbol-image" />
                    <img src={c.image} alt="symbol" className="symbol-image" />
                    <img src={c.image} alt="symbol" className="symbol-image" />
                    <div>{c.line}</div>
                    <div>{c.ratio}</div>
                  </td>
                ))}
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// src/app/components/win-conditions/win-conditions.component.ts
import { Component } from '@angular/core';
import { NgForOf } from '@angular/common';

@Component({
  selector: 'app-win-conditions',
  standalone: true,
  imports: [NgForOf],
  templateUrl: './win-conditions.component.html',
  styleUrl: './win-conditions.component.scss',
})
export class WinConditionsComponent {
  winConditions = [
    {
      symbol: '🛎️',
      image: '/assets/symbols/Bell.png',
      line: 'Any line',
      ratio: '150%',
    },
    {
      symbol: '🍒',
      image: '/assets/symbols/Cherries.png',
      line: 'Any line',
      ratio: '100%',
    },
    {
      symbol: '🍇',
      image: '/assets/symbols/Grape.png',
      line: 'Any line',
      ratio: '90%',
    },
    {
      symbol: '🍋',
      image: '/assets/symbols/Lemon.png',
      line: 'Any line',
      ratio: '80%',
    },
    {
      symbol: '🍈',
      image: '/assets/symbols/Melon.png',
      line: 'Any line',
      ratio: '70%',
    },
    {
      symbol: '🍊',
      image: '/assets/symbols/Orange.png',
      line: 'Any line',
      ratio: '60%',
    },
    {
      symbol: '⚡',
      image: '/assets/symbols/Scatter.png',
      line: 'Any line',
      ratio: '50%',
    },
    {
      symbol: '⚡',
      image: '/assets/symbols/7.png',
      line: 'Any line',
      ratio: 'Jackpot',
    },
  ];
}

<div class="container">
  <div class="win-conditions">
    <div class="table-responsive">
      <table class="table table-bordered">
        <tr>
          <td *ngFor="let condition of winConditions" class="text-center">
            <!--            <div>{{ condition.symbol }}</div>-->
            <!--            <div>{{ condition.symbol }}</div>-->
            <!--            <div>{{ condition.symbol }}</div>-->
            <img [src]="condition.image" alt="symbol" class="symbol-image" />
            <img [src]="condition.image" alt="symbol" class="symbol-image" />
            <img [src]="condition.image" alt="symbol" class="symbol-image" />
            <div>{{ condition.line }}</div>
            <div>{{ condition.ratio }}</div>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
