// src/components/overlays/WalletSelection.tsx
import type { WalletType } from '../../models/game-slot.model';
import './WalletSelection.scss';

interface WalletSelectionProps {
  onWalletChange: (wallet: WalletType) => void;
  onClose: () => void;
}

export default function WalletSelection({ onWalletChange, onClose }: WalletSelectionProps) {
  return (
    <div className="wallets">
      <div className="wallet-container flex flex-col gap-2" style={{ padding: 12 }}>
        <button
          className="close-button rounded-full border-0 bg-transparent p-0"
          onClick={(e) => { e.stopPropagation(); onClose(); }}
        >
          <img className="w-full" src="/assets/images/x-icon.png" alt="Close" />
        </button>

        <div
          className="promotion-wallet p-3"
          style={{ marginTop: 1 }}
          onClick={() => onWalletChange('promo')}
        >
          <div role="button" className="flex h-full w-full flex-col items-center">
            <div className="min-h-0 grow">
              <img alt="promotion-wallet" src="/assets/wallet/promotion-wallet.png" />
            </div>
            <div className="shrink-0">
              <img alt="promotion-wallet" src="/assets/wallet/promotion-wallet-text.png" />
            </div>
          </div>
        </div>

        <div
          role="button"
          className="primary-wallet flex flex-col p-3"
          onClick={() => onWalletChange('main')}
        >
          <div className="min-h-0 grow">
            <img alt="primary-wallet" src="/assets/wallet/primary-wallet.png" />
          </div>
          <div className="shrink-0">
            <img
              className="h-5 max-w-full w-auto"
              alt="primary-wallet"
              src="/assets/wallet/primary-wallet-text.png"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

// src/app/components/wallet-selection/wallet-selection.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CloseButtonComponent } from '../close-button/close-button.component';
import { WalletType } from '../../models/game-slot.model';

@Component({
  selector: 'app-wallet-selection',
  standalone: true,
  imports: [CloseButtonComponent],
  templateUrl: './wallet-selection.component.html',
  styleUrl: './wallet-selection.component.scss',
})
export class WalletSelectionComponent {
  @Output() walletChanged = new EventEmitter<WalletType>();
  @Output() closeWallet = new EventEmitter<void>();

  selectedWallet = 'main';

  selectWallet(wallet: WalletType) {
    this.selectedWallet = wallet;
    this.walletChanged.emit(wallet);
  }

  onCloseWallet() {
    this.closeWallet.emit();
  }
}

<div class="wallets">
  <div class="wallet-container d-flex flex-column gap-2" style="padding: 12px">
    <app-close-button
      (onclick)="onCloseWallet()"
      class="close-button"
    ></app-close-button>
    <div
      [class.active]="selectedWallet !== 'main'"
      (click)="selectWallet('promo')"
      class="promotion-wallet p-3"
      style="margin-top: 1px"
    >
      <div
        role="button"
        class="w-100 h-100 d-flex flex-column align-items-center"
      >
        <div class="flex-grow-1" style="min-height: 0">
          <img
            style=""
            alt="promotion-wallet"
            src="assets/wallet/promotion-wallet.png"
          />
        </div>
        <div class="flex-shrink-0">
          <img
            alt="promotion-wallet"
            src="assets/wallet/promotion-wallet-text.png"
          />
        </div>
      </div>
    </div>

    <div
      role="button"
      [class.active]="selectedWallet === 'main'"
      (click)="selectWallet('main')"
      class="primary-wallet d-flex flex-column p-3"
    >
      <div class="flex-grow-1" style="min-height: 0">
        <img alt="primary-wallet" src="assets/wallet/primary-wallet.png" />
      </div>
      <div class="flex-shrink-0">
        <img
          style="max-width: 100%; height: 20px; width: auto"
          alt="primary-wallet"
          src="assets/wallet/primary-wallet-text.png"
        />
      </div>
    </div>
  </div>
</div>
