// src-react/components/SpinButton.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import './SpinButton.scss';

const COUNTDOWN_TIME = 5;

interface SpinButtonProps {
  onClick: () => void;
}

export default function SpinButton({ onClick }: SpinButtonProps) {
  const defaultImage = '/assets/buttons/spin-mouse-up.png';
  const pressedImage = '/assets/buttons/spin-mouse-down.png';
  const [image, setImage] = useState(defaultImage);
  const [countdown, setCountdown] = useState<number | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const startCountdown = useCallback(() => {
    setCountdown(COUNTDOWN_TIME);
  }, []);

  useEffect(() => {
    if (countdown === null) return;
    if (countdown <= 0) {
      setCountdown(null);
      setImage(defaultImage);
      return;
    }
    timerRef.current = setInterval(() => {
      setCountdown((prev) => (prev !== null ? prev - 1 : null));
    }, 1000);
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [countdown]);

  function onSpin() {
    onClick();
    startCountdown();
  }

  return (
    <button
      onClick={onSpin}
      className="border-0 p-0 bg-transparent spin-button-wrapper"
      onMouseDown={() => setImage(pressedImage)}
      onMouseUp={() => setImage(pressedImage)}
      onTouchStart={() => setImage(pressedImage)}
      onTouchEnd={() => setImage(defaultImage)}
    >
      <img className="w-100" src={image} alt="Spin" />
      {countdown !== null && countdown > 0 && (
        <img
          className="count-down-number"
          src={`/assets/buttons/count-text/${countdown}.png`}
          alt={`${countdown}`}
        />
      )}
    </button>
  );
}

// src/app/components/spin-button/spin-button.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-spin-button',
  standalone: true,
  imports: [],
  templateUrl: './spin-button.component.html',
  styleUrl: './spin-button.component.scss',
})
export class SpinButtonComponent {
  @Output() onclick = new EventEmitter<MouseEvent>();

  defaultImage = 'assets/buttons/spin-mouse-up.png';
  pressedImage = 'assets/buttons/spin-mouse-down.png';
  buttonImage = this.defaultImage;

  changeImage(pressed: boolean) {
    this.buttonImage = pressed ? this.pressedImage : this.defaultImage;
  }
}

<button
  (click)="onSpin($event)"
  class="border-0 p-0 bg-transparent"
  (mousedown)="changeImage(true)"
  (mouseup)="changeImage(true)"
  (touchstart)="changeImage(true)"
  (touchend)="changeImage(false)"
>
  <img class="w-100" [src]="buttonImage" alt="Button Image" />
  <ng-container *ngIf="startCountdown">
    <img
      *ngFor="let img of numberImages; index as i"
      [class.d-none]="(countdown$ | async) !== numberImages.length - i"
      class="count-down-number"
      src="{{
        '/assets/buttons/count-text/' + (numberImages.length - i) + '.png'
      }}"
      alt="count-down-number"
    />
  </ng-container>
</button>
