// src-react/components/Chip.tsx
interface ChipProps {
  value: number;
  selectedValue: number;
  onClick: () => void;
}

export default function Chip({ value, selectedValue, onClick }: ChipProps) {
  const isSelected = selectedValue === value;

  return (
    <button
      className={`border-0 rounded-circle p-0 bg-transparent${isSelected ? ' selected-chip' : ''}`}
      style={{ width: 55 }}
      onClick={onClick}
    >
      <img
        className="w-100 h-100"
        src={`/assets/buttons/chips/chip-${value}.png`}
        alt={`Chip ${value}`}
      />
    </button>
  );
}

// src/app/components/chip/chip.component.ts
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
} from '@angular/core';

@Component({
  selector: 'app-chip',
  standalone: true,
  imports: [],
  templateUrl: './chip.component.html',
  styleUrl: './chip.component.scss',
})
export class ChipComponent implements OnChanges {
  @Input() value: number;
  @Output() onclick = new EventEmitter<MouseEvent>();

  buttonImage = '';

  ngOnChanges(changes: SimpleChanges) {
    this.buttonImage = `assets/buttons/chips/chip-${this.value}.png`;
  }

  changeImage(pressed: boolean) {
    // this.buttonImage = pressed ? this.pressedImage : this.defaultImage;
  }
}

<button
  [class.selected-chip]="selectedValue === value"
  style="width: 55px"
  (click)="onclick.emit($event)"
  class="border-0 rounded-circle p-0 bg-transparent"
  (mousedown)="changeImage(true)"
  (mouseup)="changeImage(false)"
  (touchstart)="changeImage(true)"
  (touchend)="changeImage(false)"
>
  <img class="w-100 h-100" [src]="buttonImage" alt="Button Image" />
</button>
